blank_issues_enabled: true
contact_links:
  - name: ğŸ–‹ï¸ Report a typo
    url: https://github.com/DraftBot-A-Discord-Adventure/DraftBot/issues?q=is%3Aopen+is%3Aissue+label%3A%22typo+%2F+visu%22++typos
    about: Pour signaler une erreur dans un texte, envoyez un commentaire sur l'issue dÃ©diÃ©e. (Si le lien, ci-dessus ne fonctionne pas, contactez nous sur discord.)
  - name: ğŸ’¡ I have an idea
    url: https://github.com/DraftBot-A-Discord-Adventure/DraftBot/discussions
    about: Vous pouvez utiliser cet espace pour nous envoyer vos suggestions.
  - name: ğŸ–ï¸ I need help !
    url: https://discord.gg/draftbot
    about: Vous pouvez poser toutes vos questions sur le serveur officiel du bot.
