name: Lib module
on:
  pull_request:
    branches:
      - draftbot-v5
    paths:
      - Lib/**

jobs:
  eslint-lib-module:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment once for all jobs
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Setup Yarn stable
      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      # Cache Yarn dependencies
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./Lib/.yarn/cache  
            ./Lib/.pnp.cjs
          key: ${{ runner.os }}-yarn-${{ hashFiles('./Lib/yarn.lock') }}

      - name: Install dependencies and Run ESLint in Lib folder
        working-directory: ./Lib
        run: |
          yarn install
          yarn eslint
